name: Deploy github bingo master

on:
  push:
    branches:
      - main
      - task/add-deployment

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          cd frontend
          npm ci
          npm run build
